publish:
  docker:
    when:
      event: tag
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/confr-sidekick
    tag:
      - latest
      - $$TAG
    archive:
      file: docker/confr-sidekick.tar
      tag: latest
cache:
  mount:
    - .git
    - docker/confr-sidekick.tar
