cache:
  mount:
    - .git
publish:
  docker:
    when:
      branch: master
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/confr-sidekick
    tag:
      - latest
