publish:
  docker:
    when:
      event: tag
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/confr-sidekick
    environment:
      NPM_CONFIG_LOGLEVEL: warn
    tag:
      - latest
      - $$TAG
