build:
  image: node:4.2.1
  environment:
    NPM_CONFIG_LOGLEVEL: warn
  commands:
    - npm i
    - npm run build
publish:
  docker:
    when:
      event: tag
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/confr-sidekick
    tag:
      - latest
      - $$TAG
