publish:
  docker:
    when:
      event: tag
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/confr-sidekick
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    tag:
      - latest
      - $$TAG
