cache:
  mount:
    - .git
publish:
  docker:
    when:
      branch: master
      event: tag
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/confr-sidekick
    tag:
      - latest
      - $$TAG
